version: "3.9"

services:
  postgres:
    image: postgres:9.4
    restart: always
    container_name: 'securitydemo-container'
    environment:
      POSTGRES_DB: securitydemodb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - 5432:5432
